version: '3.8'

services:
  challenge-container:
    image: hereisvishal/docker-challenge-metrics:v1
    ports:
      - "1234:80"
      - "9100:9100"
    networks:
      - challenge-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9100/metrics || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  metrics-scraper:
    image: alpine:latest
    depends_on:
      challenge-container:
        condition: service_healthy
    command: sh -c "apk add --no-cache curl; while true; do curl http://challenge-container:9100/metrics; sleep 10; done"
    networks:
      - challenge-network

networks:
  challenge-network:
    driver: bridge

